### PR TITLE
Update Resources page

### PR DESCRIPTION
**Pull request by jrucker2004**

### CODE REVIEW

**Comment by jrucker2004** [comment]
Last time I reached out, they were not taking on new customers, and had a 6 month backlog.  No reason to recommend them at this point.

**Comment by jrucker2004** [comment]
@wavebeem looks like the netlify build process is still happening on your instance.  Not sure how to stop that, I didn't see any settings within github to fix that.

No rush on deploying this, if you want to use it as a testing place to figure that out

**Comment by wavebeem** [comment]
@jrucker2004 Just removed my Netlify project for it. Maybe trigger another build via commit and it'll clear itself up?

**Comment by jrucker2004** [comment]
This is obsolete now, changes included in future PR

**Pull request closed without merging**
